version: '3.8'

services:
  skyticket-app:
    build: .
    restart: unless-stopped
    ports:
      - "9001:9001"
    depends_on:
      - skyticketDB-app
    networks:
        - nginx-network

  skyticketDB-app:
    image: postgres:latest
    environment:
      POSTGRES_DB: skyticketDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5495:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
        - nginx-network

networks:
  nginx-network:
    external: true